<a href="https://colab.research.google.com/github/MaverickDeAI/model2/blob/main/model_init1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

common algorithm associated with machine leaning
random forest
naive bayes
nearest neighbor
sopport vector machine
... and many more



common algorithm associated with deep leaning
neural network
fully connected neural network
convolutional neural network
Transformer
... and many more

In [3]:
print(tf.__version__)

2.15.0


In [4]:
tensor1 = tf.constant([1,2,3,4])
tensor1.ndim
dir(tensor1)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tensor__',
 '__tf_tracing_type__',
 '_

ways to create tensors
tf.constant
tf.ones
tf.random.rand

Manipulating Tensors

In [5]:
random_1 = tf.random.Generator.from_seed(42)
model = random_1.normal(shape=(1,2))
model

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.7565803 , -0.06854702]], dtype=float32)>

In [6]:
tensor2 = tf.zeros(shape =(2,3,4,5))
tensor2

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
tensor2[:2,:2,:2,:2]
t = tensor2[...,tf.newaxis]
t

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

In [24]:
tf.expand_dims(tensor2,axis=1)

<tf.Tensor: shape=(2, 1, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [29]:
v = tf.cast(tensor2 ,dtype=tf.int32);
v

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [32]:
tensor3 = tf.random.uniform(shape=[1,1,1,1,50])
tensor3

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.9718993 , 0.74942946, 0.34282017, 0.58984184, 0.7391416 ,
           0.48194718, 0.2631663 , 0.75392795, 0.18246078, 0.24217176,
           0.08568895, 0.41823184, 0.66018915, 0.64137304, 0.34669638,
           0.73787904, 0.5338707 , 0.36525297, 0.21210241, 0.92398286,
           0.676455  , 0.6237668 , 0.911566  , 0.7382457 , 0.11822534,
           0.55776787, 0.46173382, 0.36260486, 0.14256   , 0.6720637 ,
           0.7151325 , 0.06944442, 0.88623023, 0.08325696, 0.92489994,
           0.05570364, 0.80602837, 0.2368797 , 0.85201216, 0.45132923,
           0.72316337, 0.8360379 , 0.19985211, 0.6772921 , 0.01358497,
           0.20128345, 0.89634573, 0.22201777, 0.5880599 , 0.64838684]]]]],
      dtype=float32)>

In [33]:
tensor3_squeezed = tf.squeeze(tensor3)
tensor3_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.9718993 , 0.74942946, 0.34282017, 0.58984184, 0.7391416 ,
       0.48194718, 0.2631663 , 0.75392795, 0.18246078, 0.24217176,
       0.08568895, 0.41823184, 0.66018915, 0.64137304, 0.34669638,
       0.73787904, 0.5338707 , 0.36525297, 0.21210241, 0.92398286,
       0.676455  , 0.6237668 , 0.911566  , 0.7382457 , 0.11822534,
       0.55776787, 0.46173382, 0.36260486, 0.14256   , 0.6720637 ,
       0.7151325 , 0.06944442, 0.88623023, 0.08325696, 0.92489994,
       0.05570364, 0.80602837, 0.2368797 , 0.85201216, 0.45132923,
       0.72316337, 0.8360379 , 0.19985211, 0.6772921 , 0.01358497,
       0.20128345, 0.89634573, 0.22201777, 0.5880599 , 0.64838684],
      dtype=float32)>

one hot encoding (transform no numerical data to numerical data)